### ISSUE TITLE
Usage on browser environment

### ISSUE THREAD

**Issue by pedroalmeida415** [Brooooooklyn/lzma#167]
From looking through the files, I can see that there is a [browser](https://github.com/Brooooooklyn/lzma/blob/d954b731284f07d64eda7c265ac6fdf4cc88d23e/browser.js#L1) file, as well as WASM binaries, but don't see a way to use it with the package, and I can't import them in any way since they are not declared as exports in the [package.json](https://github.com/Brooooooklyn/lzma/blob/d954b731284f07d64eda7c265ac6fdf4cc88d23e/package.json#L107)

Are those just for future reference or is there any way I can use this library on a browser environment?

**Comment by cheblin** [comment]
reply from AI

Yes, you can use the `lzma` library from the `Brooooooklyn` repository in the browser. The file `lzma/browser.js` exports functionalities from `@napi-rs/lzma-wasm32-wasi`, which is suitable for WebAssembly and thus can be used in a browser environment.

Here's how you can set it up:

### Step-by-Step Guide

1. **Install the Library:**
   If you haven't already, install the `lzma` library using npm:
   ```sh
   npm install @napi-rs/lzma-wasm32-wasi
   ```

2. **Include the Script in Your HTML:**
   Create an HTML file and include a script to initialize and use the `lzma` module.
   ```html
   <!DOCTYPE html>
   <html lang="en">
   <head>
       <meta charset="UTF-8">
       <meta name="viewport" content="width=device-width, initial-scale=1.0">
       <title>LZMA in Browser</title>
       <script type="module">
           import { compress, decompress } from '@napi-rs/lzma-wasm32-wasi';

           async function runLZMA() {
               const inputString = "Hello, LZMA!";
               const encoder = new TextEncoder();
               const decoder = new TextDecoder();

               const input = encoder.encode(inputString);

               // Compress the input
               const compressed = await compress(input);
               console.log('Compressed:', compressed);

               // Decompress the input
               const decompressed = await decompress(compressed);
               console.log('Decompressed:', decoder.decode(decompressed));
           }

           runLZMA();
       </script>
   </head>
   <body>
       <h1>Check the console for LZMA compression and decompression results</h1>
   </body>
   </html>
   ```

### Explanation
- **Importing the Module:**
  ```javascript
  import { compress, decompress } from '@napi-rs/lzma-wasm32-wasi';
  ```

- **Encoding and Decoding:**
  - Use `TextEncoder` to convert the input string to a `Uint8Array`.
  - Use `TextDecoder` to convert the decompressed `Uint8Array` back to a string.

- **Compress and Decompress:**
  - `compress(input)` compresses the input `Uint8Array` and returns a promise that resolves with the compressed data.
  - `decompress(compressed)` decompresses the compressed data and returns a promise that resolves with the decompressed data.

### Summary
By using the `@napi-rs/lzma-wasm32-wasi` package, you can easily set up LZMA compression and decompression in the browser. The provided example shows how to integrate this functionality into an HTML page and handle compression and decompression using WebAssembly. This approach leverages modern JavaScript features such as ES modules and async/await for an efficient implementation.

**Comment by Brooooooklyn** [comment]
Close via https://github.com/Brooooooklyn/lzma/pull/192
